name: assignment_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  agora_rtc_engine: ^6.5.2
  permission_handler: ^12.0.0+1
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter_callkit_incoming: ^2.5.2
  flutter_local_notifications: ^19.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
